#!/bin/python3

https://www.hackerrank.com/challenges/py-if-else/problem


N = int(input())
if (N%2!=0):
    print("Weird")
elif (N%2 == 0 and (2<=N<=6)):
    print("Not Weird")
elif (N%2 == 0 and (6<=N<=21)):
    print("Weird")
elif( N%2 == 0 and N > 20):
    print("Not Weird")
else:
    print("Not Weird")
